/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVentesRouteImport } from './routes/_authenticated.ventes'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated.patients'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated.parametres'
import { Route as AuthenticatedMedicamentsRouteImport } from './routes/_authenticated.medicaments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated.assistant'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentesRoute = AuthenticatedVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicamentsRoute =
  AuthenticatedMedicamentsRouteImport.update({
    id: '/medicaments',
    path: '/medicaments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/medicaments': typeof AuthenticatedMedicamentsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/medicaments': typeof AuthenticatedMedicamentsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/medicaments': typeof AuthenticatedMedicamentsRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assistant'
    | '/dashboard'
    | '/medicaments'
    | '/parametres'
    | '/patients'
    | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assistant'
    | '/dashboard'
    | '/medicaments'
    | '/parametres'
    | '/patients'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/medicaments'
    | '/_authenticated/parametres'
    | '/_authenticated/patients'
    | '/_authenticated/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventes': {
      id: '/_authenticated/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AuthenticatedVentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medicaments': {
      id: '/_authenticated/medicaments'
      path: '/medicaments'
      fullPath: '/medicaments'
      preLoaderRoute: typeof AuthenticatedMedicamentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMedicamentsRoute: typeof AuthenticatedMedicamentsRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedVentesRoute: typeof AuthenticatedVentesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMedicamentsRoute: AuthenticatedMedicamentsRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedVentesRoute: AuthenticatedVentesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
