CREATE TABLE public.fiches_medicaments (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nom_commercial text NOT NULL,
  dci text NOT NULL,
  dosage text,
  forme text,
  classe_therapeutique text,
  laboratoire text,
  indications text,
  posologie text,
  contre_indications text,
  precautions text,
  effets_indesirables text,
  interactions text,
  conservation text,
  image_url text,
  image_source text,
  sources text NOT NULL DEFAULT '',
  date_maj date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT ON public.fiches_medicaments TO authenticated;
GRANT ALL ON public.fiches_medicaments TO service_role;

ALTER TABLE public.fiches_medicaments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Fiches lisibles par les utilisateurs connectes"
ON public.fiches_medicaments FOR SELECT TO authenticated USING (true);

CREATE INDEX idx_fiches_nom ON public.fiches_medicaments (lower(nom_commercial));
CREATE INDEX idx_fiches_dci ON public.fiches_medicaments (lower(dci));

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$
LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_fiches_updated_at BEFORE UPDATE ON public.fiches_medicaments
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO public.fiches_medicaments
(nom_commercial, dci, dosage, forme, classe_therapeutique, laboratoire, indications, posologie, contre_indications, precautions, effets_indesirables, interactions, conservation, sources, date_maj) VALUES
('Paracétamol', 'Paracétamol', '500 mg', 'Comprimé', 'Antalgique - Antipyrétique (palier I)', 'Génériques multiples', 'Douleurs légères à modérées et états fébriles.', 'Adulte : 500 mg à 1 g par prise, à renouveler après 4 à 6 heures si besoin, sans dépasser 3 g par 24 h (4 g maximum sur avis médical). Enfant : 15 mg/kg par prise toutes les 6 heures, sans dépasser 60 mg/kg/24 h.', 'Hypersensibilité au paracétamol ; insuffisance hépatocellulaire sévère.', 'Réduire la dose en cas d''insuffisance hépatique ou rénale, de dénutrition, d''alcoolisme chronique ou de poids inférieur à 50 kg. Ne jamais associer plusieurs spécialités contenant du paracétamol.', 'Rares aux doses usuelles : éruption cutanée, thrombopénie. Le surdosage expose à une atteinte hépatique grave.', 'Surveillance renforcée en cas d''association aux anticoagulants oraux (INR). Prudence avec les inducteurs enzymatiques hépatiques.', 'À conserver à une température inférieure à 30 °C, à l''abri de l''humidité.', 'OMS - Liste modèle des médicaments essentiels ; ANSM - Résumé des caractéristiques du produit (paracétamol).', '2026-09-23'),
('Amoxicilline', 'Amoxicilline', '500 mg', 'Gélule', 'Antibiotique - Pénicilline A (bêta-lactamine)', 'Génériques multiples', 'Infections ORL, bronchopulmonaires, urinaires, stomatologiques et cutanées dues à des germes sensibles.', 'Adulte : 1 à 3 g par jour en 2 à 3 prises selon l''infection. Enfant : 25 à 50 mg/kg/jour en 2 à 3 prises. Durée habituelle 5 à 10 jours selon l''indication.', 'Allergie aux pénicillines ou aux céphalosporines (allergie croisée possible).', 'Adapter la posologie en cas d''insuffisance rénale. Arrêter immédiatement en cas de manifestation allergique. Éruption fréquente en cas de mononucléose infectieuse.', 'Troubles digestifs (diarrhée, nausées), candidoses, éruptions cutanées, réactions allergiques pouvant aller jusqu''au choc anaphylactique.', 'Méthotrexate (augmentation de la toxicité), allopurinol (risque accru d''éruption). Efficacité des contraceptifs oraux possiblement diminuée.', 'À conserver à une température inférieure à 25 °C ; suspension reconstituée à conserver au frais et à utiliser sous 7 jours.', 'OMS - Liste modèle des médicaments essentiels ; ANSM - RCP amoxicilline.', '2026-09-23'),
('Métronidazole', 'Métronidazole', '500 mg', 'Comprimé', 'Antibactérien et antiparasitaire (nitro-imidazolé)', 'Génériques multiples', 'Amibiase, giardiase, trichomonase, vaginose bactérienne, infections à germes anaérobies.', 'Adulte : 500 mg 2 à 3 fois par jour selon l''indication, généralement 7 à 10 jours. Amibiase : 1,5 g/jour en 3 prises pendant 7 jours. Enfant : 30 à 40 mg/kg/jour en 3 prises.', 'Hypersensibilité aux imidazolés ; association à l''alcool et au disulfirame.', 'Éviter toute boisson alcoolisée pendant le traitement et 48 h après (effet antabuse). Prudence en cas d''antécédents neurologiques ou hématologiques ; éviter les traitements prolongés.', 'Goût métallique, nausées, coloration foncée des urines, glossite, neuropathie périphérique lors des traitements prolongés.', 'Alcool et disulfirame (contre-indiqués), anticoagulants oraux (potentialisation), lithium, busulfan.', 'À conserver à une température inférieure à 25 °C, à l''abri de la lumière.', 'OMS - Liste modèle des médicaments essentiels ; ANSM - RCP métronidazole.', '2026-09-23'),
('Artéméther + Luméfantrine (Coartem)', 'Artéméther / Luméfantrine', '20 mg / 120 mg', 'Comprimé', 'Antipaludique - Combinaison thérapeutique à base d''artémisinine (CTA)', 'Novartis et génériques préqualifiés OMS', 'Traitement du paludisme simple à Plasmodium falciparum.', 'Schéma de 6 prises sur 3 jours (à 0, 8, 24, 36, 48 et 60 heures). Adulte et enfant de plus de 35 kg : 4 comprimés par prise. Posologie pédiatrique selon le poids (5-14 kg : 1 cp ; 15-24 kg : 2 cp ; 25-34 kg : 3 cp). À prendre avec un aliment gras (lait, repas) pour l''absorption.', 'Hypersensibilité aux principes actifs ; paludisme grave (relève d''un traitement injectable) ; premier trimestre de grossesse sauf avis médical.', 'Vérifier le diagnostic (TDR ou frottis). Surveillance en cas d''allongement de l''intervalle QT ou de troubles électrolytiques. Reprendre la dose si vomissement dans l''heure.', 'Céphalées, vertiges, troubles digestifs, asthénie, palpitations, allongement du QT.', 'Médicaments allongeant le QT, inhibiteurs ou inducteurs puissants du CYP3A4, halofantrine (à éviter).', 'À conserver à une température inférieure à 30 °C, à l''abri de l''humidité.', 'OMS - Directives pour le traitement du paludisme ; Programme national de lutte contre le paludisme (Mali) ; RCP du produit.', '2026-09-23'),
('Quinine', 'Quinine (sulfate/chlorhydrate)', '300 mg', 'Comprimé', 'Antipaludique (alcaloïde du quinquina)', 'Génériques multiples', 'Traitement du paludisme, notamment lorsque les CTA ne sont pas utilisables ; paludisme grave par voie injectable en milieu hospitalier.', 'Adulte : 8 mg/kg de quinine base toutes les 8 heures pendant 7 jours. Enfant : même posologie rapportée au poids. Toute forme grave doit être traitée en milieu hospitalier.', 'Hypersensibilité à la quinine, antécédents d''hémolyse ou de fièvre bilieuse hémoglobinurique, troubles du rythme cardiaque, névrite optique.', 'Surveillance de la glycémie (risque d''hypoglycémie), du rythme cardiaque et de l''audition. Prudence chez la femme enceinte et l''insuffisant rénal ou hépatique.', 'Cinchonisme (acouphènes, baisse d''audition, vertiges, céphalées, troubles visuels), hypoglycémie, troubles digestifs, troubles du rythme.', 'Médicaments allongeant le QT, digoxine, méfloquine, antiacides (diminution de l''absorption).', 'À conserver à une température inférieure à 30 °C, à l''abri de la lumière et de l''humidité.', 'OMS - Directives pour le traitement du paludisme ; ANSM - RCP quinine.', '2026-09-23'),
('Sels de réhydratation orale (SRO)', 'Glucose et sels minéraux (formule OMS à faible osmolarité)', 'Sachet pour 1 litre', 'Poudre pour solution buvable', 'Réhydratation orale', 'UNICEF / génériques préqualifiés OMS', 'Prévention et traitement de la déshydratation liée aux diarrhées aiguës, quel que soit l''âge.', 'Dissoudre un sachet dans 1 litre d''eau potable. Après chaque selle liquide : 50 à 100 ml chez l''enfant de moins de 2 ans, 100 à 200 ml chez l''enfant plus grand, à volonté chez l''adulte. Solution à jeter après 24 heures. Associer le zinc chez l''enfant pendant 10 à 14 jours.', 'Occlusion intestinale, déshydratation sévère avec état de choc ou troubles de la conscience (réhydratation intraveineuse nécessaire), anurie.', 'Respecter strictement la dilution (ni plus ni moins d''eau). Utiliser de l''eau potable ou bouillie refroidie. Orienter en urgence en cas de signes de gravité.', 'Vomissements en cas d''ingestion trop rapide ; hypernatrémie en cas de dilution insuffisante.', 'Aucune interaction médicamenteuse notable.', 'Sachets à conserver au sec, à l''abri de la chaleur ; solution reconstituée à consommer dans les 24 heures.', 'OMS / UNICEF - Prise en charge de la diarrhée de l''enfant ; OMS - Liste modèle des médicaments essentiels.', '2026-09-23'),
('Vitamine C', 'Acide ascorbique', '500 mg', 'Comprimé', 'Vitamine hydrosoluble', 'Génériques multiples', 'Prévention et traitement des carences en vitamine C, scorbut, apports complémentaires en cas de besoins accrus.', 'Adulte : 500 mg à 1 g par jour, de préférence le matin. Scorbut : 250 mg 4 fois par jour pendant au moins 1 semaine selon avis médical.', 'Hypersensibilité, antécédents de lithiase rénale oxalique, surcharge en fer (hémochromatose, thalassémie).', 'Éviter les prises le soir (effet légèrement stimulant). Prudence en cas d''insuffisance rénale.', 'Troubles digestifs, calculs rénaux aux doses élevées prolongées.', 'Augmente l''absorption du fer ; peut fausser certains dosages biologiques (glycémie, recherche de sang dans les selles).', 'À conserver à une température inférieure à 25 °C, à l''abri de la lumière et de l''humidité.', 'ANSM - RCP acide ascorbique ; OMS - Liste modèle des médicaments essentiels.', '2026-09-23'),
('Ibuprofène', 'Ibuprofène', '400 mg', 'Comprimé', 'Anti-inflammatoire non stéroïdien (AINS)', 'Génériques multiples', 'Douleurs d''intensité légère à modérée, états fébriles, affections rhumatismales et inflammatoires.', 'Adulte : 200 à 400 mg par prise, 3 fois par jour maximum, sans dépasser 1 200 mg par 24 h en automédication. Enfant de plus de 6 mois : 20 à 30 mg/kg/jour en 3 à 4 prises. Prendre au cours d''un repas, sur la durée la plus courte possible.', 'Ulcère gastroduodénal évolutif, insuffisance hépatique, rénale ou cardiaque sévère, grossesse à partir du 6e mois, antécédent d''allergie aux AINS ou à l''aspirine, varicelle et infections évolutives.', 'Prudence chez le sujet âgé, en cas de déshydratation, d''hypertension ou d''asthme. Ne pas associer à un autre AINS.', 'Douleurs abdominales, nausées, ulcères et hémorragies digestives, céphalées, vertiges, réactions allergiques, atteinte rénale.', 'Autres AINS et aspirine, anticoagulants et antiagrégants, corticoïdes, lithium, méthotrexate, diurétiques, IEC et sartans.', 'À conserver à une température inférieure à 30 °C.', 'ANSM - RCP ibuprofène ; OMS - Liste modèle des médicaments essentiels.', '2026-09-23'),
('Cotrimoxazole', 'Sulfaméthoxazole / Triméthoprime', '400 mg / 80 mg', 'Comprimé', 'Antibactérien - Association sulfamide + diaminopyrimidine', 'Génériques multiples', 'Infections urinaires et respiratoires à germes sensibles ; prophylaxie et traitement de la pneumocystose ; prophylaxie chez les personnes vivant avec le VIH.', 'Adulte : 800 mg/160 mg (2 comprimés) 2 fois par jour. Enfant : 30 mg/kg/jour de sulfaméthoxazole et 6 mg/kg/jour de triméthoprime en 2 prises. Prophylaxie : selon le protocole national.', 'Allergie aux sulfamides, insuffisance hépatique ou rénale sévère, déficit en G6PD, nouveau-né de moins de 6 semaines, grossesse au premier trimestre et fin de grossesse.', 'Boire abondamment. Arrêter immédiatement en cas d''éruption cutanée (risque de syndrome de Lyell ou de Stevens-Johnson). Surveillance hématologique lors des traitements prolongés.', 'Éruptions cutanées parfois graves, troubles digestifs, atteintes hématologiques (neutropénie, anémie), hyperkaliémie, atteinte rénale.', 'Anticoagulants oraux, méthotrexate, phénytoïne, IEC et diurétiques épargneurs de potassium, sulfamides hypoglycémiants.', 'À conserver à une température inférieure à 25 °C, à l''abri de la lumière.', 'OMS - Liste modèle des médicaments essentiels ; ANSM - RCP cotrimoxazole.', '2026-09-23'),
('Albendazole', 'Albendazole', '400 mg', 'Comprimé à croquer', 'Antihelminthique à large spectre', 'Génériques préqualifiés OMS', 'Traitement des helminthiases intestinales (ascaridiose, ankylostomiase, trichocéphalose, oxyurose) et campagnes de déparasitage de masse.', 'Adulte et enfant de plus de 2 ans : 400 mg en prise unique (200 mg entre 1 et 2 ans). Répéter après 2 à 3 semaines en cas d''oxyurose. Traitements plus longs sous supervision médicale pour les formes tissulaires.', 'Hypersensibilité à l''albendazole ; premier trimestre de grossesse.', 'Écarter une grossesse avant traitement chez la femme en âge de procréer. Surveillance hépatique et hématologique lors des traitements prolongés.', 'Douleurs abdominales, nausées, céphalées, vertiges ; élévation des transaminases et leucopénie lors des cures prolongées.', 'Dexaméthasone, praziquantel et cimétidine (augmentation des concentrations d''albendazole).', 'À conserver à une température inférieure à 30 °C, à l''abri de l''humidité.', 'OMS - Liste modèle des médicaments essentiels ; OMS - Déparasitage préventif.', '2026-09-23'),
('Fer + Acide folique', 'Sulfate ferreux / Acide folique', '200 mg / 0,4 mg', 'Comprimé', 'Antianémique - Supplémentation martiale', 'Génériques multiples', 'Prévention et traitement de l''anémie ferriprive, notamment pendant la grossesse.', 'Prévention chez la femme enceinte : 1 comprimé par jour pendant toute la grossesse et 3 mois après l''accouchement. Traitement de l''anémie : selon avis médical, généralement 2 à 3 comprimés par jour pendant 3 mois.', 'Anémies non ferriprives, surcharge en fer (hémochromatose, thalassémie), hypersensibilité.', 'Prendre de préférence à distance du thé, du café et des produits laitiers. Prévenir le patient de la coloration noire des selles.', 'Troubles digestifs (nausées, constipation, diarrhée), coloration noire des selles, coloration dentaire avec les formes liquides.', 'Cyclines, fluoroquinolones, hormones thyroïdiennes, antiacides, calcium (espacer les prises d''au moins 2 heures).', 'À conserver à une température inférieure à 25 °C, hors de portée des enfants (risque d''intoxication grave par le fer).', 'OMS - Recommandations sur la supplémentation en fer et acide folique ; OMS - Liste modèle des médicaments essentiels.', '2026-09-23'),
('Oméprazole', 'Oméprazole', '20 mg', 'Gélule gastro-résistante', 'Inhibiteur de la pompe à protons (IPP)', 'Génériques multiples', 'Reflux gastro-œsophagien, ulcère gastrique ou duodénal, éradication d''Helicobacter pylori en association, prévention des lésions liées aux AINS.', 'Adulte : 20 mg par jour le matin avant le repas, pendant 4 à 8 semaines selon l''indication. Éradication d''H. pylori : 20 mg 2 fois par jour en association à deux antibiotiques pendant 7 à 14 jours.', 'Hypersensibilité aux IPP ; association au nelfinavir.', 'Écarter une lésion maligne avant traitement prolongé en cas de signes d''alarme. Prudence lors des traitements longs (risque d''hypomagnésémie, de carence en vitamine B12, de fractures osseuses).', 'Céphalées, troubles digestifs, éruptions cutanées ; plus rarement hypomagnésémie et infections digestives.', 'Clopidogrel (efficacité réduite), nelfinavir et atazanavir, méthotrexate, digoxine, itraconazole et kétoconazole.', 'À conserver à une température inférieure à 25 °C, à l''abri de l''humidité.', 'ANSM - RCP oméprazole ; OMS - Liste modèle des médicaments essentiels.', '2026-09-23');